version: "3"
services:
  commitleague:
    build:
      context: ../../src
      dockerfile: ../deployment/docker/commitleague/Dockerfile
    image: hadialnehlawi/commitleague
  reverseproxy:
    build:
      context: ./reverseproxy
    image: hadialnehlawi/reverseproxy
