apiVersion: v1
kind: Service
metadata:
  name: commitleague-service
spec:
  replicas: 1
  selector:
    app: commitleague
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer