apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: commitleague
  name: commitleague
spec:
  selector:
    matchLabels:
      service: commitleague
  replicas: 2
  template:
    metadata:
      labels:
        service: commitleague
    spec:
      restartPolicy: Always
      # volumes:
      #     - name: configmap-volume
      #       configMap:
      #         name: env-config
      containers:
        - name: commitleague
          image: hadialnehlawi/commitleague
          ports:
            - containerPort: 5000
          # imagePullPolicy: Always
          # resources:
          #   requests:
          #     memory: "64Mi"
          #     cpu: "250m"
          #   limits:
          #     memory: "1024Mi"
          #     cpu: "500m"
          env:
            - name: OWNER
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: OWNER
            - name: REPOSITORY
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REPOSITORY
            - name: GITHUB_OAUTH_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: GITHUB_OAUTH_CLIENT_ID
            - name: GITHUB_OAUTH_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: GITHUB_OAUTH_CLIENT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: env-secret
                  key: DATABASE_URL

